### ISSUE TITLE
error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by robsonyeg** [martinkabe/RSQLS#12]
After installing the library and call the function got error like following:

```
> library(RSQLS)
> cs <- set_connString("SERVER", "DBNAME")
> str(cs)
 chr "\"Data Source=SERVER;Initial Catalog=DBNAME;Integrated Security=True;MultipleActiveResultSets=True;\""
> foo <- get_DB_info(cs)
The system cannot find the path specified.
Error in get_DB_info(cs) : See the previous messages for more details.
```

R environment:
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSQLS_1.9

loaded via a namespace (and not attached):
[1] compiler_3.5.0    tools_3.5.0       data.table_1.11.2
```

**Comment by martinkabe** [comment]
Try to check whether **csv_to_sql_loader.exe** file is present in 
paste(system.file(package = "RSQLS")[1],"/Loader/csv_to_sql_loader.exe", sep = "")
If not then you need to copy/paste **RSQLS** folder into correct library folder.

**Comment by martinkabe** [comment]
E.g. in my case **csv_to_sql_loader.exe** file is in C:/Users/UserName/Documents/R/win-library/3.4/RSQLS/Loader/ folder because all the libs are installed into C:/Users/UserName/Documents/R/win-library/3.4 folder on my machine.

Check where are your packages being installed: **.libPaths()[1]** and just copy **RSQLS** folder there and it should work.

**Comment by robsonyeg** [comment]
Yes, the fix works. Thanks.
