### ISSUE TITLE
Only SELECT statement is allowed

### ISSUE THREAD

**Issue by jfontestad** [martinkabe/RSQLS#14]
Just started getting the following error: "Only SELECT statement is allowed".

*Note: Running the same queries in SMSS work fine.

**Query:**
SELECT DISTINCT CAST(LTRIM(RTRIM(b.Cust_ID)) AS nvarchar(MAX)) AS Cust_ID, ISNULL(CAST(s.Transact_Num AS int), 0) AS Transact_Num, CAST(LTRIM(RTRIM(e.Cust_Email)) AS nvarchar(MAX)) AS Cust_Email FROM Cust_Static b INNER JOIN Cust_Dynamic e ON (e.Cust_ID = b.Cust_ID) INNER JOIN Transactions s ON (s.Cust_ID = b.Cust_ID) WHERE (s.tKey >= 201801 AND s.tKey <= 201804) AND b.Cust_Cat = '5';

**Data Pull:**
ds.data <- as.data.frame(dpull_data(connURL.x, ds.qry, showprogress = TRUE))
*Also tried with : 
ds.data<- as.data.frame(pull_data(connURL.x, ds.qry, showprogress = TRUE))

-------------

Also tried placing in global temp table:
**Query:**
SELECT * CAST(LTRIM(RTRIM(jf.Cust_ID)) AS nvarchar(MAX)) AS Cust_ID, ISNULL(CAST(jf.Transact_Num AS int), 0) AS Transact_Num, CAST(LTRIM(RTRIM(jf.Cust_Email)) AS nvarchar(MAX)) AS Cust_Email FROM ##jf_tmp jf;

**Data Pull:**
ds.data <- as.data.frame(dpull_data(connURL.x, ds.qry, showprogress = TRUE))
*Also tried with : 
ds.data<- as.data.frame(pull_data(connURL.x, ds.qry, showprogress = TRUE))

*****************
This could possibly be due to a \n being inserted somewhere in the backend when submitting the query and the server is expecting a query in that new line.

**Comment by martinkabe** [comment]
Could you install newer RSQLS package (install_github("martinkabe/RSQLS")) try it again and let me know.
Thanks.

**Comment by jfontestad** [comment]
Have no idea what dpull is. program knows only push or pull as a first argument!

**Comment by jfontestad** [comment]
Have no idea what pull is. program knows only push or pull as a first argument!

**Comment by martinkabe** [comment]
Could you install package once again and try your query again as well?

**Comment by jfontestad** [comment]
Query now runs. 
Issue seems to be fixed.
Again, thanks you!

**Comment by martinkabe** [comment]
Thank you too.
