### ISSUE TITLE
send_SQL_task

### ISSUE THREAD

**Issue by jfontestad** [martinkabe/RSQLS#16]
Issue template
Would send_SQL_task be the optimal way to run a query and have results inserted into a table and/or temp table?

i.e.:
SELECT * 
INTO AIRPLANECARS
FROM AIRPLANES

SELECT * 
INTO ##AIRPLANECARS
FROM AIRPLANES

**Comment by jfontestad** [comment]
I ask because although it does allow me to do it. It spits out an error.

**Comment by martinkabe** [comment]
If I just replicate what you wrote above on my own machine

create table dbo.SomeTable
(
	id int null,
	name varchar(5) null
)

insert into dbo.SomeTable values
(1,'name1'),(2,'name2'),(3,'name3')

create table dbo.SomeTable_2
(
	id int not null,
	name varchar(5) null
)

library(RSQLS)
send_SQL_task(set_connString("LAPTOP-USERNAME\\SQLEXPRESS", "SomeDBName"),
              "insert into SomeTable_2 select * from SomeTable")

I'm not getting any error and can see the data in SomeTable_2 table.

But if you are trying to do the same with #temptable, it won't work. #temptable is created with particular connection and in this particular case the connection lives with send_SQL_task method. Once this method is done, connection is no longer there and the same is for #temptable.

Is that what you are asking?

**Comment by martinkabe** [comment]
If you are only trying to retrieve some data from db, just use dpull_data or pull_data methods. You can see the result of your query inside R env stored as data.frame or data.table.

**Comment by jfontestad** [comment]
> send_SQL_task(connURL.x, tblQry)

You can CREATE, DELETE or DROP table.
If you want return something from DB, use parametrized version: pull_data(connectionString = , sqltask = , showprogress = FALSE)!
Please, see the documentation!

**Comment by jfontestad** [comment]
In these situations, I'm not trying to retrieve any data in that instance, but generating some temp data that is stored in a temp table on the server that other queries utilize to retrieve data.

**Comment by martinkabe** [comment]
No, this is not an error message, this is only printed info tells that you can use pull_data or dpull_data methods to retrieve some data using SELECT statement. It won't throw any error.

I've implemented simple algo on backend side which is trying to find any SELECT statement inside user's query and if it is there it just prints this 'advice' or option how to retrieve some data from db side.
