### ISSUE TITLE
Cannot find data type bool

### ISSUE THREAD

**Issue by makfuksy** [martinkabe/RSQLS#17]
When creating a new table with push_data, data frame bool column is not created and the statement fails.

Table ITM_SD_SLA_Details doesn't exit in database. Creating it...
Column, parameter, or variable #3: Cannot find data type bool.
[1] "Data Frame has 1 rows and 5 columns."

**Comment by martinkabe** [comment]
Could you send me dframe subset for debugging purposes?
		
		

		Get Outlook for iOS
	




On Tue, Jul 3, 2018 at 3:50 AM +0200, "M.Fuksi" <notifications@github.com> wrote:












When creating a new table with push_data, data frame bool column is not created and the statement fails.

**Comment by martinkabe** [comment]
`fdsfd`

**Comment by martinkabe** [comment]
This issue has been fixed. You can download new RSQLS version which could handle this issue:

`library(devtools)
install_github("martinkabe/RSQLS", force=T)
df <- data.frame(name=c("Name1","Name2"),
                 married=c(TRUE, FALSE))

cs <- set_connString("LAPTOP-NAME\\SQLEXPRESS", "RSQLS")
push_data(cs, df, "dbo.BoolData", append = T, showprogress = T)
p_df <- dpull_data(cs, "select * from dbo.BoolData", showprogress = T)`

**Comment by martinkabe** [comment]
This issue has been fixed. You can download new RSQLS version which could handle this issue:

`library(devtools)`
`install_github("martinkabe/RSQLS", force=T)`
`df <- data.frame(name=c("Name1","Name2"), married=c(TRUE, FALSE))`
`cs <- set_connString("LAPTOP-NAME\SQLEXPRESS", "RSQLS")`
`push_data(cs, df, "dbo.BoolData", append = T, showprogress = T)`
`p_df <- dpull_data(cs, "select * from dbo.BoolData", showprogress = T)`
