### ISSUE TITLE
how to set the encoding?

### ISSUE THREAD

**Issue by wikithink** [martinkabe/RSQLS#19]
Issue template
there are some messy codes when pull data from local sqlserver? eg. chinese character.

**Comment by martinkabe** [comment]
Could you provide me piece of data resulting in 'weird' characters? I cannot reproduce an issue from what you provided so far.

1. Provide chunk of data
2. check you sql server settings:
select SERVERPROPERTY('Collation') -- check collation determines encoding in SQL
3. check sessionInfo (utils package) from your R.
