### ISSUE TITLE
supress messages from push_data

### ISSUE THREAD

**Issue by ghost** [martinkabe/RSQLS#20]
Is there a way to suppress the output messages from push_data (i.e. pushing data into xxx without showing progress...)?  I have the function as part of a loop and the messages are filling up the screen.  I have tried using capture.output and sink but so far I have not been able to hide the messages.

**Comment by martinkabe** [comment]
You can try showprogress = FALSE parameter.

`push_data(connString, df, sqltabname, append = TRUE, showprogress = FALSE, quotes = "auto", separator = '|')`

**Comment by ghost** [comment]
I do have showprogess = FALSE, but I still get these messages with every call to push_data

[1] Data Frame has 214 rows and 18 columns.

Pushing data into xxx table without showing progress
Pipe is used as separator.
214 records imported
This operation took
Minutes: 0
Seconds: 0
Milliseconds: 238.6375

**Comment by martinkabe** [comment]
I just released 2.9 pckg version where should be fix for this. You can try and let me know if works.

**Comment by ghost** [comment]
Hello, I started receiving the error "object 'show_progress' not found".  I don't think you define the variable 'show_progress' before using it in push_data.

**Comment by martinkabe** [comment]
Hi, looks like
`devtools::document()`
didn't build correct version of my changes. You can try now and let me know how it goes.

**Comment by ghost** [comment]
works great, thank you!
