### ISSUE TITLE
To CRAN?

### ISSUE THREAD

**Issue by michaellevy** [martinkabe/RSQLS#8]
Do you plan to submit this to CRAN? Looks like a useful package for us, but we'd rather only depend on CRAN packages.

**Comment by martinkabe** [comment]
Thanks, I appreciate it. Yes, that's the plan. I'll submit package to CRAN asap.

**Comment by michaellevy** [comment]
Thanks. For what it's worth, I don't think this will work for us if it only runs on Windows.

**Comment by kthy** [comment]
@michaellevy it's literally the first line under prerequisites: "Windows OS"…
