### ISSUE TITLE
Package for AutoDetectCsvSeparator missing?

### ISSUE THREAD

**Issue by kthy** [martinkabe/RSQLS#9]
I'm trying to build the csv loader .exe locally to test a modification. I'm getting the following output:

    S:\Forks\RSQLS\inst\Loader>csc -define:DEBUG -optimize -out:csv_to_sql_loader2.exe *.cs
    Microsoft (R) Visual C# Compiler version 2.7.0.62707 (75dfc9b3)
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Functions.cs(370,38): error CS0103: The name 'AutoDetectCsvSeparator' does not exist in the current context

Googling tells me that `AutoDetectCsvSeparator` might come from a GemBox package named `ExcelFile`?

**Comment by martinkabe** [comment]
Aha, sorry, I'll push it asap.

**Comment by martinkabe** [comment]
done!
